version: 0.2
phases:
  install:
    runtime-versions:
        php: 7.3
  pre_build:
    commands:
      - echo "[+] Pre BUild...."
  build:
    commands:
      - echo "[+] Unit TEst...."
  post_build:
    commands:
      - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
  artifacts:
    files: imagedefinitions.json