version: 0.1
phases:
  install:
    runtime-versions:
        php: 7.3
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - echo "[+] Unit TEst...."
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"