version: 0.2
phases:
  install:
    runtime-versions:
        php: 7.3
  pre_build:
    commands:
      - echo "[+] Pre BUild...."
  build:
    commands:
      - echo "[+] Unit TEst...."
  post_build:
    commands:
      - printf 'TESTCODE' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json